version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fastmark
      POSTGRES_PASSWORD: password
    ports:
      - 54320:5432

  queue:
    image: rabbitmq
    container_name: fastmark_queue
    ports:
      - 5672:5672

  worker:
    build:
      context: ./backend
      dockerfile: worker.Dockerfile
    command: dramatiq api --watch .
    env_file:
      - docker.env
    depends_on:
      - queue
      - db
    volumes:
      - ./backend/src/api:/app/api
      - ./uploads:/app/uploads

  api:
    build: ./backend
    env_file:
      - docker.env
    depends_on:
      - queue
      - db
      - worker
    ports:
      - '5000:5000'
    volumes:
      - ./backend/src/api:/app/api
      - ./uploads:/app/uploads